### ISSUE TITLE
Not getting the exact procedure how to install

### ISSUE THREAD

**Issue by ghost** [tumi8/hloc#1]
Hi, Hope you find well can you please guide me to install this software in my pc, i have ubuntu version 16 i run the following command (pip install -r requirements.txt) your guidance is required in this matter.
Thank you.

**Comment by sattler** [comment]
Hi, which Python version do you run and what is the exact error you get?

**Comment by ghost** [comment]
python 3.4

**Comment by ghost** [comment]
can you please guide me how to install it properly, i am not getting proper information to run this application.

**Comment by sattler** [comment]
So like the guide says you need to execute pip install -r requirements.txt

The requirements.txt file is located in the root of the repo.
Could you explain in 1 to 2 sentences what you try to do with our framework?

**Comment by ghost** [comment]
i am student and i want to learn the algorithm and working of your framework.
i am newbie in python and intermediate knowledge of matlab, do you have any reference of your work in matlab.

**Comment by ghost** [comment]
i have also tryied to implement constraint based geo-location on matlab.

**Comment by sattler** [comment]
No I am sry we have no work done in matlab. Also our framework does not use a special algorithm for geolocation. We rather search for location code hints in the domain name and try to verify these with simple RTT measurements. If you just want to understand that algorithm you can read our [paper](https://arxiv.org/abs/1706.09331).

Pip the program you were not able to run is the [python package manager](https://en.wikipedia.org/wiki/Pip_(package_manager))

**Comment by ghost** [comment]
ok thank you i will check this tomorrow then contact to you soon.

**Comment by ghost** [comment]
Sir, could you please provide me the data set? I am working on MATLAB

**Comment by sattler** [comment]
Hi sry for the delay. The branch [tma17](https://github.com/tumi8/hloc/tree/tma17) contains some explanations where to find the data and how to read it. But it does not contain all measurements. Only the closest one is kept. It's for others to validate our results. I think that it is not possible to make this data useful for your own algorithm.

**Comment by ghost** [comment]
Sir,
Thanks for the reply. I only work on MATLAB and I know its programming only. I will start learning python after 9th of May.
Then I will work on this code. I had semester project to implement the paper and propose new idea. So, I did it.

As soon as I learn Python, will implement your algorithm. And will mail you again.

Thank you so much.
Sincerely,
M Tehreem
________________________________
