### ISSUE TITLE
Getting Geolocation Coordinates from .found json file

### ISSUE THREAD

**Issue by alexthemonk** [tumi8/hloc#2]
Hi, 
I was following through the steps in README (on branch tma17) and got the .found file generated after the "Find" step. I'm not sure how I should interpret the information from the .found file. Specifically how should I generate the geolocation results in terms of Lat Lon from the result. 
Thank you very much.

**Comment by sattler** [comment]
for each domain/domain label you get the corresponding location hints. These hints contain the location id. The location id can than be matched against your locations input file to find the hints lat/lon

**Comment by alexthemonk** [comment]
Thank you so much. 
A quick follow up question, the .found json files have keys labeled in numbers. (For example the following image) I wasn't able to find documentations for these labels. 
Just wondering whether you could help me with understanding the meaning of each fields. 
Thank you for your time
![image](https://user-images.githubusercontent.com/30848036/77175964-66757f80-6a91-11ea-8033-afd60dabcefb.png)

**Comment by sattler** [comment]
Use `json_load` from [data_processing/util](https://github.com/tumi8/hloc/blob/tma17/src/data_processing/util.py#L204) to load this file. It will convert this unreadable json file into objects defined in the same util file.

I hope this helps

**Comment by alexthemonk** [comment]
Thanks, that's very helpful.
