### ISSUE TITLE
cities1000.txt missing

### ISSUE THREAD

**Issue by colinmccann** [tumi8/hloc#6]
When running the example-initial-db-setup script:

**Error**
File "/Users/colin/dev/ixmaps/hloc/hloc/scripts/codes_parser.py", line 406, in get_geo_names
    with open(file_path, encoding='utf-8') as geoname_file:
FileNotFoundError: [Errno 2] No such file or directory: 'location-data/cities1000.txt'

**Method description from get_geo_names**
"""Get the geo names from file ./collectedData/cities1000.txt"""

I assume the method description is wrong. Where can I obtain cities1000.txt? Is that what you are referring to here:
_"We produce a daily export with all location hints for all domains with the minimal RTT measurement to the corresponding IP address. The file contains the following columns (the csv column title is in brackets):"_

**Comment by colinmccann** [comment]
I found the necessary files on a different branch, which also contains easier to follow setup instructions

**Comment by sattler** [comment]
You should get the latest file from geonames.org in order to not use the 3 years old file from our publication.

Download Link:
http://download.geonames.org/export/dump/
